name: Dev Deployment
on:
  push:
    branches:
      - main
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Deploy Dev Bild
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build-dev # will run `yarn build` command
      - name: Upload Dev Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dev-build-artifacts
          path: dist/
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build_dev]
    steps:
      - name: Download Dev Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dev-build-artifacts
          path: dist/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1
      - name: Deploy content to S3 bucket
        run: aws s3 sync dist/ s3://${{ secrets.S3_UI_BUCKET_DEV }} --delete
      - name: Invalidate Cloudfront Distribution
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID_DEV }}
